# Generated by Django 2.0.7 on 2018-11-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0003_remove_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
